# Generated by Django 4.1.5 on 2023-03-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Comment')),
                ('updatedat', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
